apiVersion: v1
kind: ConfigMap
metadata:
  name: db-sql
data:
  01-BucketList.sql: |-
    CREATE DATABASE BucketList;
    CREATE TABLE `BucketList`.`tbl_user` (
      `user_id` BIGINT UNIQUE AUTO_INCREMENT,
      `user_name` VARCHAR(45) NULL,
      `user_username` VARCHAR(45) NULL,
      `user_password` VARCHAR(45) NULL,
      PRIMARY KEY (`user_id`));

  02-tbl_wish.sql: |-
    USE BucketList;
    CREATE TABLE `tbl_wish` (
      `wish_id` int(11) NOT NULL AUTO_INCREMENT,
      `wish_title` varchar(45) DEFAULT NULL,
      `wish_description` varchar(5000) DEFAULT NULL,
      `wish_user_id` int(11) DEFAULT NULL,
      `wish_date` datetime DEFAULT NULL,
      PRIMARY KEY (`wish_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

  sp_addwish.sql: |-
    USE BucketList;
    DELIMITER $$
      CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_addWish`(
          IN p_title varchar(45),
        IN p_description varchar(1000),
        IN p_user_id bigint
      )
      BEGIN
        insert into tbl_wish(
          wish_title,
          wish_description,
          wish_user_id,
          wish_date
        )
        values
        (
          p_title,
          p_description,
          p_user_id,
          NOW()
        );
      END$$
      DELIMITER ;

      ;
  
  sp_createUser.sql: |-
    USE BucketList;
    DELIMITER $$
    CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_createUser`(
        IN p_name VARCHAR(20),
        IN p_username VARCHAR(20),
        IN p_password VARCHAR(20)
    )
    BEGIN
        if ( select exists (select 1 from tbl_user where user_username = p_username) ) THEN
            select 'Username Exists !!';
        ELSE
            insert into tbl_user
            (
                user_name,
                user_username,
                user_password
            )
            values
            (
                p_name,
                p_username,
                p_password
            );
        
        END IF;
    END$$
    DELIMITER ;


  sp_GetWishById.sql: |-
    USE BucketList;
    DELIMITER $$
    CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_GetWishById`(
    IN p_wish_id bigint,
    In p_user_id bigint
    )
    BEGIN
    select * from tbl_wish where wish_id = p_wish_id and wish_user_id = p_user_id;
    END

  sp_GetWishByUser: |-
    USE BucketList
    DELIMITER $$
    CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_GetWishByUser`(
    IN p_user_id bigint,
    IN p_limit int,
    IN p_offset int,
    out p_total bigint
    )
    BEGIN
      select count(*) into p_total from tbl_wish where wish_user_id = p_user_id;
      SET @t1 = CONCAT( 'select * from tbl_wish where wish_user_id = ', p_user_id, ' order by wish_date desc limit ',p_limit,' offset ',p_offset);
      PREPARE stmt FROM @t1;
      EXECUTE stmt;
      DEALLOCATE PREPARE stmt;
    END$$
    DELIMITER ;

  sp_validateLogin.sql: |-
    USE BucketList;
    DELIMITER $$
    CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_validateLogin`(
    IN p_username VARCHAR(20)
    )
    BEGIN
        select * from tbl_user where user_username = p_username;
    END$$
    DELIMITER ;
